name: CR_101 CI
  
on:
  push:
    branches:
      - cr_101
      #- release_101

jobs:
  test:
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run test
        run: |
          cd cicd_demo
          python -c "from calculator  import addition; assert addition(2,3)==5"
          python -c "from calculator  import subtraction; assert subtraction(5,3)==2"
          echo "Test passed again!" >> result.txt
    
      - name: Upload Test Result
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: cicd_demo/result.txt

      - name: Publish result
        run: |
          echo "### CI Result" >> $GITHUB_STEP_SUMMARY
          echo "✅ addition(2,3) passed" >> $GITHUB_STEP_SUMMARY